name: Debug GitHub Event Payload

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - assigned
      - unassigned

jobs:
  debug-github-event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine Event Type
        run: |
          echo "Triggered by GitHub Event: ${{ github.event_name }}"

      - name: Print GitHub Event Payload
        run: |
          echo "GitHub Event Payload:"
          echo '${{ toJSON(github.event) }}' | jq .

      - name: Save GitHub Event Payload to File
        run: |
          echo '${{ toJSON(github.event) }}' | jq . > github_event_payload.json
          echo "Event payload saved to github_event_payload.json"

      - name: Upload GitHub Event Payload
        uses: actions/upload-artifact@v3
        with:
          name: github-event-payload
          path: github_event_payload.json
